### ISSUE TITLE
Strange event KeyboardInterrupt when running with pm2

### ISSUE THREAD

**Issue by aseques** [gorakhargosh/watchdog#789]
I am using a tool called pm2 to run several tasks that I want to be online all the time and be respawned if they die (serveral of them are nodejs), I wanted to use it's ecosystem file (a yaml file that starts the environment) because is the more clear way to manage the tasks

If I start watchmedo with a simple command (--version) it works without issue
```
apps:
    - script: watchmedo
      interpreter: python3
      name: watch-bancs
      args: --version
      #args: shell-command --command='pwd' /tmp/
      log_date_format: YYYY-MM-DD HH:mm:ss
```
But when I add some more complex comands (this is just a minimal case to reproduce) it just stops, but the strange thing is that it seems to stop because of a keyboard interrupt.
```
apps:
    - script: watchmedo
      interpreter: python3
      name: watch-bancs
      args: shell-command --command='pwd' /tmp/
      log_date_format: YYYY-MM-DD HH:mm:ss
```
The log
```
30|watch-bancs  | 2021-05-07 15:57:20: Traceback (most recent call last):
30|watch-bancs  | 2021-05-07 15:57:20:   File "/usr/local/bin/watchmedo", line 8, in <module>
30|watch-bancs  | 2021-05-07 15:57:20:     sys.exit(main())
30|watch-bancs  | 2021-05-07 15:57:20:   File "/home/oper/.local/lib/python3.8/site-packages/watchdog/watchmedo.py", line 616, in main
30|watch-bancs  | 2021-05-07 15:57:20:     parser.dispatch()
30|watch-bancs  | 2021-05-07 15:57:20:   File "/usr/lib/python3/dist-packages/argh/helpers.py", line 55, in dispatch
30|watch-bancs  | 2021-05-07 15:57:20:     return dispatch(self, *args, **kwargs)
30|watch-bancs  | 2021-05-07 15:57:20:   File "/usr/lib/python3/dist-packages/argh/dispatching.py", line 174, in dispatch
30|watch-bancs  | 2021-05-07 15:57:20:     for line in lines:
30|watch-bancs  | 2021-05-07 15:57:20:   File "/usr/lib/python3/dist-packages/argh/dispatching.py", line 277, in _execute_command
30|watch-bancs  | 2021-05-07 15:57:20:     for line in result:
30|watch-bancs  | 2021-05-07 15:57:20:   File "/usr/lib/python3/dist-packages/argh/dispatching.py", line 231, in _call
30|watch-bancs  | 2021-05-07 15:57:20:     result = function(namespace_obj)
30|watch-bancs  | 2021-05-07 15:57:20:   File "/home/oper/.local/lib/python3.8/site-packages/watchdog/watchmedo.py", line 380, in log
30|watch-bancs  | 2021-05-07 15:57:20:     observe_with(observer, handler, args.directories, args.recursive)
30|watch-bancs  | 2021-05-07 15:57:20:   File "/home/oper/.local/lib/python3.8/site-packages/watchdog/watchmedo.py", line 114, in observe_with
30|watch-bancs  | 2021-05-07 15:57:20:     time.sleep(1)
30|watch-bancs  | 2021-05-07 15:57:20: KeyboardInterrupt
```

The same command launched from command line works without issues (monitoring /tmp/ for events)
`watchmedo shell-command --command=pwd  /tmp/`

I am quite lost with this, any ideas? I don't even know if it's on whatchdog part or pm2

I forgot to add platform and versions:

- python 3.8.5
- ubuntu 20.04
- whatchdog 2.1.0
